### ISSUE TITLE
WikiPathwaysCache gets stuck after 50-70 pathways

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/wikipathways-api-client-java#2]
For some reason (maybe too many requests to the server?) the script gets stuck when the cache needs to be rebuild from scratch. 
Possible solutions:
- generate new client object every 30 pathways to limit number of requests per thread
- include a short waiting time after each pathway (tested but does not work!)
- test another HTTP library
- update HTTP client library to version 4.4
- test other Java version (it seems to be working on pathvisio server)
- other ideas?

**Comment by fdlk** [comment]
Hi, I _think_ I ran into this issue when using your library to access WikiPathways.
The getPathwayAs method does not close the content InputStream, and therefore each request to getPathwayAs will lock one more http connection from the pool, till all connections are in use.

I've created a pull request with a fix for this specific method. Most of the other methods in the interface use Utils.connect which does not suffer from this problem. So how long it takes for the entire pool to hang depends on what proportion of your requests is a getPathwayAs request that nibbles one connection from the pool.

To determine if you are experiencing the same issue, you could create a thread dump when the script is stuck and see if they resemble this one (a HttpClient waiting for a connection from the pool):

```
"qtp189888904-197" #197 prio=5 os_prio=31 tid=0x00007fd893ebb000 nid=0x6123 waiting on condition [0x000000011d67a000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000007a0f4baf0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at org.apache.http.pool.PoolEntryFuture.await(PoolEntryFuture.java:133)
    at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:282)
    at org.apache.http.pool.AbstractConnPool.access$000(AbstractConnPool.java:64)
    at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:177)
    at org.apache.http.pool.AbstractConnPool$2.getPoolEntry(AbstractConnPool.java:170)
    at org.apache.http.pool.PoolEntryFuture.get(PoolEntryFuture.java:102)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:244)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:231)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:173)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
[...]
```

**Comment by mkutmon** [comment]
Thanks for this fix.
