### ISSUE TITLE
Remote Exception: Error finding pathways by Xref

### ISSUE THREAD

**Issue by vcnainala** [wikipathways/wikipathways-api-client-java#6]
Hi, 

I was trying to find wiki pathways by Xref ( using ChEbi ids ) using the wikipathways java api client. It was running fine on my local machine but when I tried it on the production server its failing. I looked into the source code but could not find the actual cause. It would be really helpful if you could help me debugging this. 

Thanks in advance.

Error message: 

java.rmi.RemoteException: Connect to webservice.wikipathways.org:80 [webservice.wikipathways.org/169.230.76.84] failed: Connection timed out; nested exception is: 
        java.net.ConnectException: Connection timed out
        at org.pathvisio.wikipathways.webservice.WikiPathwaysRESTBindingStub.findPathwaysByXref(WikiPathwaysRESTBindingStub.java:147)
        at org.wikipathways.client.WikiPathwaysClient.findPathwaysByXref(WikiPathwaysClient.java:414)
        at uk.ac.ebi.metabolights.referencelayer.importer.ReferenceLayerImporter.getPathways(ReferenceLayerImporter.java:532)
        at uk.ac.ebi.metabolights.referencelayer.importer.ReferenceLayerImporter.chebiEntity2Metabolights(ReferenceLayerImporter.java:411)
        at uk.ac.ebi.metabolights.referencelayer.importer.ReferenceLayerImporter.importMetabolitesFromChebi(ReferenceLayerImporter.java:253)
        at uk.ac.ebi.metabolights.controller.MetaboliteImporterController$1.run(MetaboliteImporterController.java:104)
Caused by: java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.wikipathways.client.utils.Utils.connect(Utils.java:58)
        at org.pathvisio.wikipathways.webservice.WikiPathwaysRESTBindingStub.findPathwaysByXref(WikiPathwaysRESTBindingStub.java:138)
        ... 5 more

**Comment by egonw** [comment]
Hi @CS76, it's a "Connection timed out" message, meaning that the server did not reply an answer in time... this could have been a temporary glitch...
